# Created by: AI Agent
# Date: 2026-02-06T22:56:44-05:00
# Last Modified By: Claude Code (Claude Sonnet 4.5)
# Last Modified: 2026-02-14T16:15:00-05:00

baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'Your Name'
theme = 'coreydaley-dev'

[pagination]
  pagerSize = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # Add your images to static/images/ directory
  avatar = '/images/avatar.jpg'
  coverImage = '/images/cover.jpg'
  description = 'A blog about some really cool stuff'
  tagline = 'Your Awesome Tagline'

  # Enable special date avatar swapping (e.g., Halloween, Christmas, etc.)
  # Set to false to disable automatic avatar changes on holidays
  enableCheckSpecialDate = false

[params.social]
  # Social media links - only configured links will be displayed
  github = 'https://github.com/yourusername'
  linkedin = 'https://linkedin.com/in/yourusername'
  twitter = 'https://twitter.com/yourusername'
  facebook = 'https://facebook.com/yourusername'
  instagram = 'https://instagram.com/yourusername'
  mastodon = 'https://mastodon.social/@yourusername'
  bluesky = 'https://bsky.app/profile/yourusername.bsky.social'
  youtube = 'https://youtube.com/@yourusername'
  reddit = 'https://reddit.com/u/yourusername'
  stackoverflow = 'https://stackoverflow.com/users/yourid/yourname'
  email = 'your@email.com'

[params.tracking]
  # googleAnalytics = 'G-XXXXXXXXXX'
