baseURL = 'https://coreydaley.dev/'
languageCode = 'en-us'
title = 'Corey Daley'
theme = 'github-style'
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Corey Daley"
  description = "Software Engineer | Secure Software Development & Cybersecurity | Embracing AI, writing code in Go and Python"
  github = "coreydaley"
  linkedin = "coreydaley-dev"
  email = "corey@coreydaley.dev"
  url = "https://coreydaley.dev"
  keywords = "blog, google analytics"
  rss = false
  lastmod = true
  userStatusEmoji = "ðŸ˜€"
  favicon = "/images/github.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "Elizabethtown, KY"
  # custom_css = ["css/custom.css"]
  # custom_js = ["js/custom.js"]
  enableSearch = true
