baseURL = 'https://coreydaley.dev/'
languageCode = 'en-us'
title = 'Corey Daley'
theme = 'coreydaley-dev'

[pagination]
  pagerSize = 10

googleAnalytics = 'G-21PJ0PFQM1'
[params]
  # Add your images to static/images/ directory
  avatar = '/images/avatar.png'
  coverImage = '/images/cover.png'
  description = 'Technical blog about software engineering and AI development'
  tagline = 'Software Engineer & AI Enthusiast'

  about = 'Passionate software engineer exploring AI, automation, and developer tools. Writing about what I learn along the way.'
[params.social]
  github = 'https://github.com/coreydaley'
  linkedin = 'https://linkedin.com/in/coreydaley-dev'
  twitter = 'https://twitter.com/coreydaley_dev'
  facebook = 'https://facebook.com/coreydaley.dev'
  email = 'corey@coreydaley.dev'

#[params]
#  author = "Corey Daley"
#  description = "Software Engineer & AI Enthusiast | Secure Software Development & Cybersecurity | Writing code in Go and Python"
#  github = "coreydaley"
#  linkedin = "coreydaley-dev"
#  facebook = "coreydaley.dev"
#  twitter = "coreydaley_dev"
#  email = "corey@coreydaley.dev"
#  url = "https://coreydaley.dev"
#  keywords = "blog, google analytics"
#  rss = false
#  lastmod = true
#  userStatusEmoji = "ðŸ˜€"
#  favicon = "/images/github.png"
#  avatar = "/images/avatar.png"
#  headerIcon = "/images/github-mark-white.png"
#  location = "Elizabethtown, KY"
#  # custom_css = ["css/custom.css"]
#  # custom_js = ["js/custom.js"]
#  enableSearch = true
