# Created by: AI Agent
# Date: 2026-02-04T14:35:03-05:00

name: Add PR to Project

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/coreydaley/projects/1
          github-token: ${{ secrets.GH_ACTIONS_ACCESS }}
